---
- hosts: localhost
  gather_facts: false

  vars_files:
    - "{{ playbook_dir }}/../../vars/main.yml"
    - "{{ playbook_dir }}/../../defaults/template_info.yml"
    - "{{ playbook_dir }}/../../defaults/secrets.yml"

  pre_tasks:
    - name: Ensure needed ssh keys are created.
      community.crypto.openssh_keypair:
        path: "{{ sshkey_folder }}/{{ item }}-{{ project_name }}"
      with_items:
        - "{{ root_username }}"

    - name: "Ensure {{ sshkey_folder }}/known_hosts exists"
      ansible.builtin.copy:
        content: ""
        dest: "{{ sshkey_folder }}/known_hosts"
        force: false
        mode: 0664

    - name: "Ensure 'terraform.tfvars' template is deployed"
      ansible.builtin.template:
        src: "{{ playbook_dir }}/../../templates/{{ item }}_terraform.tfvars.j2"
        dest: "{{ playbook_dir }}/../../../terraform/{{ item }}/vm/terraform.tfvars"
      loop: "{{ host_list.keys() }}"

  tasks:
    - name: Ensure each host is deployed with terraform on digitalocean.
      community.general.terraform:
        project_path: "{{ playbook_dir }}/../../../terraform/digitalocean/vm"
        variables_files: "{{ playbook_dir }}/../../../terraform/digitalocean/vm/terraform.tfvars"
        force_init: true
      register: terraform_infra_digitalocean
      when: host_list['digitalocean'][0] is defined

    - name: Ensure each host is deployed with terraform on hetzner.
      community.general.terraform:
        project_path: "{{ playbook_dir }}/../../../terraform/hetzner/vm"
        variables_files: "{{ playbook_dir }}/../../../terraform/hetzner/vm/terraform.tfvars"
        force_init: true
      register: terraform_infra_hetzner
      when: host_list['hetzner'][0] is defined

    - name: Add each deployed digitalocean host to ansible inventory.
      ansible.builtin.add_host:
        hostname: "{{ item.value.ipv4_address }}"
        groups: "{{ item.value.tags }}"
      changed_when: false
      with_dict: "{{ terraform_infra_digitalocean.outputs.vms.value }}"
      when: terraform_infra_digitalocean.outputs.vms.value is defined

    - name: Add each deployed hetzner host to ansible inventory.
      ansible.builtin.add_host:
        hostname: "{{ item.value.ipv4_address }}"
        groups: "{{ item.value.labels.keys() }}"
      changed_when: false
      with_dict: "{{ terraform_infra_hetzner.outputs.vms.value }}"
      when: terraform_infra_hetzner.outputs.vms.value is defined      
