---
- hosts: localhost
  gather_facts: false

  vars_files:
    - "{{ playbook_dir }}/../../defaults/template_info.yml"
    - "{{ playbook_dir }}/../../defaults/secrets.yml"

  tasks:
    - name: Ensure all host are destroyed with terraform
      community.general.terraform:
        project_path: "{{ playbook_dir }}/../../../terraform/"
        variables_files: "{{ playbook_dir }}/../../../terraform/terraform.tfvars"
        state: absent

    - name: Ensure local ssh keys are destroyed
      ansible.builtin.file:
        path: "{{ sshkey_folder }}/{{ item }}-{{ project_name }}"
        state: absent
      with_items:
        - "{{ root_username }}"

    - name: Remove hosts from inventory
      meta: refresh_inventory
