---
- hosts: localhost
  gather_facts: false

  vars_files:
    - "{{ playbook_dir }}/../../vars/main.yml"
    - "{{ playbook_dir }}/../../defaults/template_info.yml"
    - "{{ playbook_dir }}/../../defaults/secrets.yml"

  tasks:
    - name: Ensure host is destroyed with terraform on {{ _cloud_provider }}.
      community.general.terraform:
        project_path: "{{ playbook_dir }}/../../../terraform/{{ _cloud_provider }}/vm"
        variables_files: "{{ playbook_dir }}/../../../terraform/{{ _cloud_provider }}/vm/terraform.tfvars"
        state: absent

    - name: Ensure local ssh keys are destroyed
      ansible.builtin.file:
        path: "{{ sshkey_folder }}/{{ item }}-{{ project_name }}"
        state: absent
      with_items:
        - "{{ root_username }}"

    - name: Remove hosts from inventory
      meta: refresh_inventory
