---
- ansible.builtin.import_playbook: tasks/terraform/create.yml
  tags: always

- ansible.builtin.import_playbook: tasks/terraform/destroy.yml
  tags: ['never', 'destroy']

- hosts: localhost
  gather_facts: false
  pre_tasks:
    - name: Get required roles with Ansible Galaxy
      ansible.builtin.command: ansible-galaxy install -r files/requirements.yml -p roles/
      delegate_to: localhost
      changed_when: false
      tags: always

- hosts: all
  vars_files:
    - "{{ playbook_dir }}/defaults/main.yml"
    - "{{ playbook_dir }}/defaults/template_info.yml"

  vars:
    ansible_user: "{{ root_username }}"
    ansible_ssh_private_key_file: "{{ root_private_key_path }}"
  
  tasks:
    - name: Bootstrap host with barebones config
      ansible.builtin.import_tasks: tasks/bootstrap/main.yml
      tags: ['never', 'create']

## add your plays here
# 
# - hosts: all
#   vars:
#     ansible_user: "{{ root_username }}"
#     ansible_ssh_private_key_file: "{{ root_private_key_path }}"
# 
#   tasks:
#     - name: Your tasks here
#       ansible.builtin.import_tasks: tasks/main.yml
#       tags: always
# 