---
- ansible.builtin.import_playbook: tasks/terraform/create.yml

- hosts: group_1
  vars_files:
    - "{{ playbook_dir }}/defaults/main.yml"
    - "{{ playbook_dir }}/defaults/template_info.yml"

  vars:
    ansible_user: "{{ root_username }}"
    ansible_ssh_private_key_file: "{{ root_private_key_path }}"

  pre_tasks:
    - name: Get required roles with Ansible Galaxy
      ansible.builtin.command: ansible-galaxy install -r files/requirements.yml -p roles/
      delegate_to: localhost
      changed_when: false

    - name: Bootstrap host with barebones config
      ansible.builtin.include_tasks: tasks/bootstrap/main.yml

  tasks:
    - name: Your tasks here
      ansible.builtin.include_tasks: tasks/main.yml

- ansible.builtin.import_playbook: tasks/terraform/destroy.yml
  tags: ['never', 'destroy']
